### ISSUE TITLE
German bibliography

### ISSUE THREAD

**Issue by sojaworks** [IMAGINARY/SNAPSHOTS#59]
Concerns German snapshots only: Several authors are separated by "and" instead of "und". And, of course, there should be no serial comma. Example: 
Now: Sample, J., Example, K., and Somebody, T: A Book we wrote together. 
How it should be: Sample, J., Example, K. und Somebody, T: A Book we wrote together.

**Comment by helmut2** [comment]
I do not (yet) know too much about the habits in mathematical literature nor about the way LaTeX handles citations. But I'd like to mention that Stephan Klaus regards any solution to be sufficiant that separates the auhors, e.g. "Sample, J.; Example, K.; Somebody, T.: A Book we wrote together." 
This would seperate the way of citation from the language used in the article.
If there is an easy way to achieve that simplified aim, we are free to do so.

**Comment by porst17** [comment]
This would again involve hacking the current third-party bibliography style file `amsplain.bst` and distributing it along with `snapshotmfo.cls` (see above). The class wouldn't be self contained anymore, which is something I would like to avoid.

In addition, the translation of `and` in the list of authors might not be the only translation issue (i.e. we would need to take an in-depth look into `amsplain.bst` to find the other spots, if any).

`babelbib` seems to be the cleaner option. But I am still awaiting the confirmation of the editors (@cederbaum) as stated above. 

Note that I created a branch (https://github.com/IMAGINARY/SNAPSHOTS/tree/babelbib) for testing the class when `babelbib` is used.

**Comment by porst17** [comment]
Proposed `babelbib` solution implemented in 47b73883198f9839c75869d9a3500e5854f9fbf1.
