### ISSUE TITLE
PDF Metadata

### ISSUE THREAD

**Issue by cederbaum** [IMAGINARY/SNAPSHOTS#64]
PDF metadata like author, title etc. is currently missing.

**Comment by helmut2** [comment]
Bofore answering thorougly, I'll try to find out, where PDF metadata show up an which metadata fields do exist. Meanwhile ...
... manually setting the metadata seems a reasonable solution for about a dozen snapshots per year, as we will probably have. Moreover this guarantees the quality of the metadata.
Which fields to use and how to fill them seems strongly related to the DOI metadata and should therefore discussed with Tatjana Ruf and Verena Franke.

**Comment by porst17** [comment]
PDF metadate show up when you ask your PDF viewer to show the document preferences. Or you can use `pdfinfo` on the command line. The data is also used by search engines for indexing.

I would be good if you could discuss the conceptional details, e.g. which metadata to include into which PDF metadata field. I am currently using the `hyperref` package for setting the data (I think this is pretty standard). But maybe there are other packages with allow to set more meta data fields (if any).

I am already working on a preliminary implementation of the meta data inclusion which extracts most of the data from macros like `\author`, `\title` etc. I am going to commit this tomorrow asap.

**Comment by porst17** [comment]
I added a new `pdfmetadata` branch in a23d9bdbbfdda8863092c96fb0528c456066752d. The following standard meta data entries are automatically set:
 * `Author`: by converting the author list given by the `\author`command, e.g. `\author{Author 1 \and Author 2}` will be converted into `Author 1, Author 2` (note that unnecessary spaces are trimmed)
 * `Title`: using the title given by `\title`
 * `Subject`: the text of the abstract

In addition, the following non-standard tags are set: `Volume` (the year part of the snapshot), `Issue` (the id of the snapshot), as well as `DOI`, `MathematicalSubjects`, `ConnectedFields`, `SeniorEditor`, `JuniorEditor`, `Director` which correspond to the data given on the last page of each snapshot. These fields are usually not read by PDF viewers (but Adobe Acrobat does and search engines can also retrieve this data if they search the PDF information catalog for things like DOI etc.)

I have to say that I had a pretty hard time converting all this data into the appropriate format such that it works with `hyperref`. Although I made quite a few tests, I can not guarantee that all data is handled correctly for any input. This is especially true for the author, title and abstract. But it is easy to work around most problems.

Say you have something like
```
\title{About the statement $A\rightarrow B$}
```
 This will be converted to `About the statement A B` in the metadata (commands unsupported by hyperref are just expanded to the empty string). Using the `\texorpdfstring` command of `hyperref, you can write this as 
```
\title{About the statement \texorpdfstring{$A\rightarrow B$}{A -> B}}
```
which gives the desired result `About the statement A -> B` (kind of).

**Comment by porst17** [comment]
Do you think the above solution is appropriate and sufficient? I also read about inclusion of XMP meta data which is a standardized format understood by a wide rang of programs and search engines. But maybe this already to much. Please let me know. XMP is completely new to me.

**Comment by porst17** [comment]
Provided solution has been accepted. XMP usage has been postponed to future releases.

**Comment by RufT** [comment]
I tested the automatic setting of the pdf metadata with the data of several old snapshots and some additional special cases. 

Names of authors with special characters worked mostly fine. Some were displayed correctly  in the metadata (e.g. accents), some have been automatically replaced by an appropriate character (e.g. vowels with ogonek bow have been replaced by the corresponding vowel), which is also ok. The only problem arose with the name McCarthy, where the "c" of the "Mc" had been raised with M\raise.5ex\hbox{c}Carthy. I tried to solve this by using the command \texorpdfstring, but that did not seem to work within this particular field. However, one could set the name by hand in the Acrobat then.

With regard to the title the workaround with \texorpdfstring worked fine. Perhaps one has to be sometimes "creative" in rewriting the title. For example, I tested some titles with greek characters and rewrote them as words (e.g. Gamma).

With regard to the abstract, I realized a problem when other environments are used within the abstract. This is for example the case with the snapshot on the ternary Goldbach problem (\begin{quote}...\end{quote} within the abstract). This produced lots of error messages. Again, this could be solved by using the \texorpdfstring-command for the whole abstract. However, the authors might not know this and might be confused. I wonder if

- we should prepare the abstract-environment in the template already with something like \begin{abtsract}\texorpdfstring{%place your abstract here}{%will be filled out by editors}\end{abstract}
- or we should add a comment to use the command \texorpdfstring when using other environments within the abstracts
- or we should add a comment to avoid other environments within the abstract at all.

What do you think?

**Comment by porst17** [comment]
Thank you for your extensive testing. 

I can confirm the broken `\texorpdfstring` command within `\author`. I opened the new issue #81 for it.

When using `\texorpdfstring`, one almost always has to be creative. But it is possible to use unicode characters, i.e. you could write `\textorpdfstring{$\beta$}{β}`. Currently, there is a still a bug preventing it from working. I created the new issue #80.

Hyperref is unable to strip away environments in the meta data for some reason. I am still investigating this. Nevertheless, one of your suggestions should be implemented. I will comment on it once I know if the automatic conversion of environment is feasible or not.

**Comment by porst17** [comment]
The issue remaining with the abstract has been outsources to #82.

**Comment by porst17** [comment]
The mentioned issues (#80, #81, #82) have been fixed and can be re-tested again (of course, I also tested them but not with all the different snapshots).
