### ISSUE TITLE
Compilation errors in abstract when environments are used

### ISSUE THREAD

**Issue by porst17** [IMAGINARY/SNAPSHOTS#82]
The abstract
```
\begin{abstract}
    Some test
    \begin{quote}
        A quote
    \end{quote}
   Some more text
\begin{abstract}
```
won't compile since `hyperref` is unable to strip away LaTeX environment code from the text.

**Comment by porst17** [comment]
The fix is two-fold.
 1. I created a patch for the `hyperref` package which currently has a bug causing the usage of LaTeX environments in PDF meta data to fail. The bug has been reported to the author of `hyperref` and is also discussed [here](http://tex.stackexchange.com/questions/231523/strip-environment-command-in-hyperref-pdf-meta-data) (by me).
 1. Many useful LaTeX environments cause paragraph breaks (like `quote`) which are entirely unsupported by `hyperref`. Therefore, I added an optional parameter to the `abstract` environment where you (or the author himself) can place the plain text version of the abstract. In `template.tex`, it now looks like this:

  ```
  \begin{abstract}[Plain text abstract used as PDF meta data (optional)]
  This is your abstract. It should give ...
  \end{abstract}
  ```

This should be self-explaining, i.e. we don't need further comments.

@RufT: Do you think this is a sufficient solution?

**Comment by RufT** [comment]
Excellent! Thank you!
